name: Monitor X Profile

on:
  schedule:
    - cron: '*/5 * * * *'  # 5分間隔で自動実行
  workflow_dispatch:       # 手動実行も可能

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Restore state cache
        uses: actions/cache@v3
        with:
          path: last_state.txt
          key: x-state-${{ github.run_id }}
          restore-keys: x-state-

      - name: Install dependencies
        run: pip install selenium discord-webhook chromedriver-autoinstaller beautifulsoup4

      - name: Run X monitor
        env:
          DISCORD_WEBHOOK_B: ${{ secrets.DISCORD_WEBHOOK_B }}
          X_TARGET_URL: ${{ secrets.X_TARGET_URL }}
        run: python monitor_x.py

      - name: Upload HTML dump
        uses: actions/upload-artifact@v4
        with:
          name: x_html_dump
          path: html_dump.txt
